name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  
  # Deploy:

  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: EC2 connection test
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ''
  #       username: ''
  #       key: ''
  #       command_timeout: 3m
  #       script: |
  #         sudo apt-get update
  #         sudo apt-get -y upgrade
  #         cd {프로젝트 폴더 위치}
  #         source {가상환경 이름}/bin/activate
  #         git pull
  #         sudo lsof -t -i tcp:8000 | xargs kill -9
  #         pip install -r requirements.txt
  #         python manage.py makemigrations
  #         python manage.py migrate
  #         nohup gunicorn --bind 0.0.0.0:8000 {django 프로젝트명}.wsgi > nohup.out 2> nohup.err < /dev/null &
  #         exit 0

  # https://velog.io/@hnnynh/Github-Actions%EB%A1%9C-%EA%B0%84%EB%8B%A8%ED%95%98%EA%B2%8C-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94